"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

fsmonitor.backend = "watchman"
fsmonitor.watchman.register-snapshot-trigger = true

[user]
name = "Pranav Sivaraman"
email = "pranavsivaraman@gmail.com"

[signing]
behavior = "drop"
backend = "ssh"
key = "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIFFUrmk5b/h/0BXe0ZvWPErKIy1GTCuFrWIXKYqJU8rnAAAAC3NzaDpzaWduaW5n ssh:signing"

[git]
subprocess = true
sign-on-push = true

[ui]
default-command = "status"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
paginate = "never"

[revsets]
log = "(trunk()..@):: | (trunk()..@)-"
