"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

fsmonitor.backend = "watchman"
fsmonitor.watchman.register-snapshot-trigger = true

[user]
name = "Pranav Sivaraman"
email = "pranavsivaraman@gmail.com"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
l = ["log", "-r", "(trunk()..@):: | (trunk()..@)-"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]

[signing]
behavior = "drop"
backend = "ssh"
key = "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIFFUrmk5b/h/0BXe0ZvWPErKIy1GTCuFrWIXKYqJU8rnAAAAC3NzaDpzaWduaW5n ssh:signing"
# key = "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAICyJUXqtqOPWimeGajDa0czr4ZyOUyccW7TSlYELR4oEAAAAC3NzaDpzaWduaW5n"

[git]
sign-on-push = true

[ui]
default-command = "status"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
paginate = "never"

[templates]
commit_trailers = "format_signed_off_by_trailer(self)"
